### ISSUE TITLE
Strict Typing?

### ISSUE THREAD

**Issue by michael-rubel** [bastinald/laravel-livewire-ui#2]
Hello! Great job, really!

I noticed you have weak typing (and missing docblocks) at all the components available. 
I know is there are stubs to modify, but most *junior-mids* will not go make the code stricter and will just use it as it is.

Do you have any plans to improve the code quality of the package?

**Comment by MACscr** [comment]
PR’s are welcomed. You can also point out improvements in future with a bit more tact.

- Mark

**Comment by bastinald** [comment]
you can use your own stubs
