### ISSUE TITLE
Question: Does this work with or Can we change Bootstrap to TailwindCSS? 

### ISSUE THREAD

**Issue by milanchheda** [bastinald/laravel-livewire-ui#3]
Hey,

First of all, thank you very much for the excellent package. 

I wanted to check if the components can be changed from Bootstrap to TailwindCSS? I understand, this package along with others use Bootstrap. But we are using TailwindCSS and wanted to check with you if there is an option to change Bootstrap to TailwindCSS.?

Thanks again,
Milan

**Comment by MACscr** [comment]
Absolutely. You just update all the stubs and blades with the new tailwind markup and remove the links to bootstrap assets and add the tailwind ones.

- Mark

**Comment by milanchheda** [comment]
Thanks Mark. Great, I'll try modifying the stubs for blades.
Another quick on this, I noticed in the video that this package has those 6-7 included packages too. Is there a way to disable some, if required? For example, if I don't need honey package, can I remove it?

**Comment by MACscr** [comment]
Of course. As always, you will want to keep track of your changes with your own git repo so that you can keep track of your changes in case you want to utilize any of the future features/fixes, etc from this repo.

**Comment by milanchheda** [comment]
Thanks Mark. Much appreciated. 👍🏼

**Comment by MACscr** [comment]
Just a follow up, but if you really are going to go the tailwind route and in the spirit of open source, fork this repo, implement your tailwind changes and open to the public as well as I am sure others could benefit from it.

**Comment by milanchheda** [comment]
Sure thing, Mark. Thanks.
