### ISSUE TITLE
Installation throws "Permission Denied" error.

### ISSUE THREAD

**Issue by MGeurts** [bastinald/laravel-livewire-ui#4]
After installation, the site throws an "Persmission denied" error.

`file_get_contents(D:\LARAGON\www\laravel-hp\app/Http/Livewire\Auth): failed to open stream: Permission denied`

php artisan migrate:auto throws the same error.

**Comment by bastinald** [comment]
This is an OS-specific perm error that you can resolve using the windows filesystem.

Google how to fix file perm errors on windows, or use linux instead :P
